sub_reddit_catalog_dict = {
	'Boobs_Nipples': [
		"https://www.reddit.com/r/FantasticBreasts/",
		"https://www.reddit.com/r/bigtitspics/",
		"https://www.reddit.com/r/AbcdTits/",
		"https://www.reddit.com/r/BustyNaturals/",
		"https://www.reddit.com/r/topless/",
		"https://www.reddit.com/r/burstingout/",
		"https://www.reddit.com/r/hugeboobs/",
		"https://www.reddit.com/r/Titties/",
		"https://www.reddit.com/r/nip_slips/",
		"https://www.reddit.com/r/B_Cups/",
		"https://www.reddit.com/r/naturaltitties/",
		"https://www.reddit.com/r/Nipples/",
		"https://www.reddit.com/r/homegrowntits/",
		],

	"Nudes": [
		"https://www.reddit.com/r/AlldayfuckNSFW/",
		"https://www.reddit.com/r/Porn__Central/",
		"https://www.reddit.com/r/AmateurXXX/",
		"https://www.reddit.com/r/BornToBeFucked/",
		"https://www.reddit.com/r/tiktoksweets/",
		"https://www.reddit.com/r/ElegantNSFW/",
		"https://www.reddit.com/r/MommyMaterial/",
		"https://www.reddit.com/r/SexyTummies/",
		"https://www.reddit.com/r/womenarethings/",
		"https://www.reddit.com/r/JizzedToThiss/",
		"https://www.reddit.com/r/realmoms/",
		"https://www.reddit.com/r/webcamgirlsnsfw/",
		"https://www.reddit.com/r/CamSluts/",
		"https://www.reddit.com/r/PerfectBody/",
		"https://www.reddit.com/r/AdorableNudes/",
		"https://www.reddit.com/r/CamGirls/",
		"https://www.reddit.com/r/WideHipsNSFW/",
		"https://www.reddit.com/r/nsfw2/",
		"https://www.reddit.com/r/BabesNSFW/",
		"https://www.reddit.com/r/ThickThighs/",
		"https://www.reddit.com/r/skinnytail/",
		"https://www.reddit.com/r/HotBunnies/",
		"https://www.reddit.com/r/RealCute/",
		"https://www.reddit.com/r/horny/",
		"https://www.reddit.com/r/NSFW_Social/",
		"https://www.reddit.com/r/TwentyPlus/",
		"https://www.reddit.com/r/naughtychicks/",
		"https://www.reddit.com/r/Nsfw_Amateurs/",
		"https://www.reddit.com/r/NSFWGirl/",
		"https://www.reddit.com/r/GirlsGW/",
		"https://www.reddit.com/r/naughtychicks/",
		"https://www.reddit.com/r/NSFWverifiedamateurs/",
		"https://www.reddit.com/r/GreatView/",
		"https://www.reddit.com/r/slutwife/",
		"https://www.reddit.com/r/420_Girls/",
		"https://www.reddit.com/r/TwentyPlus/",
		],

	"Ass": [
		"https://www.reddit.com/r/booty_queens/",
		"https://www.reddit.com/r/RateMyAss_/",
		"https://www.reddit.com/r/ButtsAndBareFeet/",
		"https://www.reddit.com/r/booty/",
		"https://www.reddit.com/r/Lovelyasses/",
		"https://www.reddit.com/r/pawg/",
		"https://www.reddit.com/r/Classy_asses/",
		"https://www.reddit.com/r/bigassaltgirls/",
	],
}
